### ISSUE TITLE
Payment sequence

### ISSUE THREAD

**Issue by kopnin** [interledger/js-ilp#24]
@emschwartz 
Hi Evan,

Could you help me, please. I have a look into the sample of ilp client and notice that receiver create a request to the sender before payment, isn't it? Why do you use this scheme? Is it means that if I would like to make a payment I have to notify receiver before and ask him to generate request?

**Comment by adrianhopebailie** [comment]
@kopnin 

This is not a prerequisite for all ILP payments but this is how the [Simple Payment Setup Protocol](https://github.com/interledger/rfcs/blob/master/0009-simple-payment-setup-protocol/0009-simple-payment-setup-protocol.md) works. 

It's possible to setup the payment differently (i.e. without the receiver participating) but currently the reference client uses SPSP.

**Comment by emschwartz** [comment]
@adrianhopebailie that is not 100% correct. `js-ilp` has this flow because it implements the [`Interledger Payment Requests`](https://github.com/interledger/rfcs/blob/master/0011-interledger-payment-request/0011-interledger-payment-request.md) spec. SPSP also uses this, but right now it is the recommended flow for most applications.

@kopnin In Interledger payments the sender and recipient need to decide upon what success "looks like" before the sender initiates the payment. The simplest way to do this is to have the recipient generate an [`Interledger Payment Request`](https://github.com/interledger/rfcs/blob/master/0011-interledger-payment-request/0011-interledger-payment-request.md), which the sender then fulfills. That is what this library implements.

There is an alternative to using payment requests and hash preimage crypto conditions that uses public keys but this is not yet implemented. The idea is that the sender creates the payment and sets the condition to the recipient's signature on a standardized form of the payment details. This way the sender needs to get the recipient's public key but doesn't need to talk to them every time.

Is there a specific use case you're interested in where implementing the sender -> recipient communication is especially inconvenient?

**Comment by kopnin** [comment]
@adrianhopebailie @emschwartz 
Thank you, guys. it's very helpful. 

@emschwartz No, I don't have any special cases. I just to figure out how it works. I try to connect 2 diff ledgers. When I faced on with the _Interledger Payment Request_  I decided that it's slight inconvenient (+ one additional point of failure) and seems like overhead on the network. How the recv should send his requests? Is it possible to do it over the Connector?

**Comment by emschwartz** [comment]
Interledger Payment Requests + `js-ilp` are intended for building ILP into other protocols. They don't specify how to communicate the requests from one end to the other because the best way to do that depends a lot on what you're building this into.

For example, a while back I was working on integrating ILP into a torrent client. In that case, the seeder requests money from the sender when they need to pay more and there is already a communication channel between the seeder and downloader.

**Comment by kopnin** [comment]
Yes, make sense. I understood, thanks for good example.

**Comment by emschwartz** [comment]
👍 let us know if you have any more questions

**Comment by adrianhopebailie** [comment]
@emschwartz can you clarify how those pieces fit together these days.

Does either js-ilp or js-ilp-core implement SPSP or just Interledger Payment Requests? Do we have reference SPSP client?

**Comment by emschwartz** [comment]
- `js-ilp-core` - should/will implement binary packet format, routing tables, quoting protocol
- `js-ilp` - implements Interledger Payment Requests. in the future it may add support for a public key-based alternative to IPR
- SPSP - we don't have an implementation of that right now. the best things to use on that level at the moment are the `five-bells-wallet` and `five-bells-wallet-client`. we may change those to use more standard SPSP once that spec has been finalized more. Note that SPSP will use IPRs and thus `js-ilp` for a JS implementation
